run:
  timeout: 10m
  skip-files:
    - mockgen_test.go
  skip-dirs:
    - vendor
    - configs
    - app/baseapp
    - .git
    - .idea

linters-settings:

  dupl:
    threshold: 100 # минимальный размер последовательности как клона

  exhaustive:
    default-signifies-exhaustive: false # default по умолчанию исчерпывающее

  funlen:
    lines: 100 # максимальное количество строк кода
    statements: 50 # максимальное количество конструкций

  goconst:
    min-len: 2 # длина повторяющейся строки
    min-occurrences: 2 # количество повторений одного и того же выражения

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

  gocyclo:
    min-complexity: 25 # чиклическая сложность

  goimports:
    local-prefixes: imgservice

  gomnd:
    settings:
      mnd:
        # don't include the "operation" and "assign"
        checks: argument,case,condition,return

  govet:
    check-shadowing: true

  lll:
    line-length: 200 # максимальная длина строки

  misspell:
    locale: US # язык для поиска текстовых ошибок/опечаток

  nolintlint:
    allow-leading-space: true # don't require machine-readable nolint directives (i.e. with no leading space)
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped

service:
  golangci-lint-version: 1.41.1

linters:
  disable-all: true
  enable:
    - govet # Suspicious constructs
    - errcheck # Unchecked errors
    - staticcheck # Static analysis checks
    - unused # Unused constants, variables, functions
    - gosimple # Simplify a code
    - structcheck # Unused struct fields
    - varcheck # Unused global variables and constants
    - ineffassign # Unused assignments to existing variables
    - deadcode # Unused code
    - typecheck # Parses and type-checks Go code
    - revive # Style mistakes
    - rowserrcheck # database/sql.Rows.Err() checked
    - stylecheck # golint analogue
    - unconvert # Unnecessary type conversions
    - goconst # Repeated strings that could be replaced by a constant
    - gofmt # Whether the code was gofmt-ed
    - goimports # Unused imports
    - misspell # Misspelled English words in comments
    - lll # Long lines
    - unparam # Unused function parameters
    - nakedret # Naked returns in functions greater than a specified function length (?)
    - exportloopref # Unpinned variables in go programs
    - gochecknoinits # No init functions are present in Go code
    - whitespace # Detection of leading and trailing whitespace
    - goprintffuncname # Printf-like functions are named with f at the end
    - nolintlint # Ill-formed or insufficient nolint directives
    - depguard # Package imports are in a list of acceptable packages
    - wsl # Forces you to use empty lines!
    - goerr113 # Check the errors handling expressions

  # - gomnd # Detect magic numbers
  # - gocyclo # Checks the cyclomatic complexity of functions
  # - bodyclose # HTTP response body is closed successfully
  # - gosec # Security problems
  # - prealloc # Slice declarations that could potentially be preallocated
  # - goerr113 # Check the errors handling expressions
  # - dupl # Code clone detection
  # - funlen # Long functions
  # - dogsled # Assignments with too many blank identifiers (e.g. x, , , _, := f())
  # - gocritic # The most opinionated Go source code linter
  # - asciicheck # Non-ASCII identifiers
  # - exportloopref # Exporting pointers for loop variables
  # - exhaustive # Exhaustiveness of enum switch statements
  # - gochecknoglobals # No globals are present in Go code
  # - gocognit # Cognitive complexity of functions
  # - godot # Comments end in a period
  # - godox # Detection of _FIXME, _TODO and other comment keywords
  # - nestif # Deeply nested if statements
  # - gomodguard # Block list linter for direct Go module dependencies
  # - testpackage # Use a separate _test package
  # - maligned # Structs that would take less memory if their fields were sorted
